### ISSUE TITLE
not compatible with assign function

### ISSUE THREAD

**Issue by kaji331** [renkun-ken/pipeR#68]
I try assign some qplot objects of ggplot2 by pipeR to new variables. Failed

**Comment by renkun-ken** [comment]
Would you please provide a simple sample?

**Comment by kaji331** [comment]
library(ggplot2)
for (i in 1:8)
    (qplot(1:i) + xlab("test")) %>>% (assign(paste("test",i,sep="_"),.))
objects()
# [1] "i"

for (i in 1:8)
    assign(paste("test",i,sep="_"),qplot(1:i) + xlab("test"))
objects()
# [1] "i" "test_1" "test_2" "test_3" .etc

**Comment by renkun-ken** [comment]
Currently, you can use the following work-around to solve your problem:

```r
(qplot(1:i) + xlab("test")) %>>% (assign(paste("test",i,sep="_"),., globalenv()))
```

to force the assignment to happen in the global environment.

The problem is in the evaluation environment. Both pipeR and magrittr (`%>%`) evaluates the expression (`assign("a", .)`) in a temporary environment in which `.` represents the piped object and whose parent environment is the calling environment of the pipe operator. 

The implementation of `eval` is that 

```r
eval(quote(assign("x", 1:n)), list(n = 10), envir)
```

The assignment is not directly evaluated at `envir` but at a temporary environment (with `n = 10`) whose parent is `envir`. The enclosing environment (`envir`) is only used for finding symbols not present in the list.

**Comment by kaji331** [comment]
Thanks for your help!

--- 原始邮件 ---

发件人： "Kun Ren" <notifications@github.com>
已发： 2015年10月23日 下午6:19
收件人： "renkun-ken/pipeR" <pipeR@noreply.github.com>
抄送： "kaji331" <kaji331@hotmail.com>
主题： Re: [pipeR] not compatible with assign function (#68)

Currently, you can use the following work-around to solve your problem:

```r
(qplot(1:i) + xlab("test")) %>>% (assign(paste("test",i,sep="_"),., globalenv()))
```

to force the assignment to happen in the global environment.

The problem is in the evaluation environment. Both pipeR and magrittr (`%>%`) evaluates the expression (`assign("a", .)`) in a temporary environment in which `.` represents the piped object and whose parent environment is the calling environment of the pipe operator.

The implementation of `eval` is that

```r
eval(quote(assign("x", 1:n)), list(n = 10), envir)
```

The assignment is not directly evaluated at `envir` but at a temporary environment (with `n = 10`) whose parent is `envir`. The enclosing environment (`envir`) is only used for finding symbols not present in the list.


---

**Comment by renkun-ken** [comment]
Just to note, the following function can enhance `eval` by allowing assignment in enclosing environment as if `expr` were evaluated in the calling environment.

```r
ev <- function(expr, data = NULL, symbol = ".") {
  expr <- substitute(expr)
  enclos <- parent.frame()
  envir <- new.env(FALSE, enclos, 1L)
  envir[[symbol]] <- data
  lockBinding(symbol, envir)
  res <- withVisible(eval(expr, envir))
  rm(list = symbol, pos = envir, inherits = FALSE)
  list2env(as.list.environment(envir), enclos)
  if (res$visible) res$value else invisible(res$value)
}
```

**Comment by renkun-ken** [comment]
@kaji331, with enhanced evaluation method, now modifying calling environment by `assign` or expressions in `{}` blocks are possible, as if they were directly evaluated in the calling environment.

The latest version with f42bf35 allows you to run code like

```r
for(i in 1:10) rnorm(i) %>>% (assign(paste0("var", i), .))
```
