### ISSUE TITLE
Have you thought of creating a pipeR version %<>>% of magrittr %<>%?

### ISSUE THREAD

**Issue by zyxdef** [renkun-ken/pipeR#70]
That would be useful and (hopefully) not very hard to code.

Nice work, by the way!  =D

Also, I'm not sure if this would be the appropriate channel for a suggestion.  If its not, then please forgive me.

**Comment by yanlinlin82** [comment]
I guess it is not pipeR's philosophy to clone another version of everything in magrittr. :P

**Comment by zyxdef** [comment]
Sounds fair.  =)
